apiVersion: v1
kind: Service
metadata:
  name: kart-api
  labels:
    run: kart-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kart-api
    type: LoadBalancer